version: "3.8"
services:
  postgre:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
       - ./nytaxi_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "81:80"
    restart: unless-stopped
    depends_on:
      - postgre

    